{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "4d1747e6-2ece-430e-b04f-9ea8c77a9c24",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1. RAW DATA INFO\n",
      "Shape: (891, 12)\n",
      "   PassengerId  Survived  Pclass  \\\n",
      "0            1         0       3   \n",
      "1            2         1       1   \n",
      "2            3         1       3   \n",
      "3            4         1       1   \n",
      "4            5         0       3   \n",
      "\n",
      "                                                Name     Sex   Age  SibSp  \\\n",
      "0                            Braund, Mr. Owen Harris    male  22.0      1   \n",
      "1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   \n",
      "2                             Heikkinen, Miss. Laina  female  26.0      0   \n",
      "3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   \n",
      "4                           Allen, Mr. William Henry    male  35.0      0   \n",
      "\n",
      "   Parch            Ticket     Fare Cabin Embarked  \n",
      "0      0         A/5 21171   7.2500   NaN        S  \n",
      "1      0          PC 17599  71.2833   C85        C  \n",
      "2      0  STON/O2. 3101282   7.9250   NaN        S  \n",
      "3      0            113803  53.1000  C123        S  \n",
      "4      0            373450   8.0500   NaN        S  \n",
      "\n",
      "Data Types:\n",
      "PassengerId      int64\n",
      "Survived         int64\n",
      "Pclass           int64\n",
      "Name               str\n",
      "Sex                str\n",
      "Age            float64\n",
      "SibSp            int64\n",
      "Parch            int64\n",
      "Ticket             str\n",
      "Fare           float64\n",
      "Cabin              str\n",
      "Embarked           str\n",
      "dtype: object\n",
      "\n",
      "Missing Values:\n",
      "PassengerId      0\n",
      "Survived         0\n",
      "Pclass           0\n",
      "Name             0\n",
      "Sex              0\n",
      "Age            177\n",
      "SibSp            0\n",
      "Parch            0\n",
      "Ticket           0\n",
      "Fare             0\n",
      "Cabin          687\n",
      "Embarked         2\n",
      "dtype: int64\n",
      "Filled missing Age with mean: 29.69911764705882\n",
      "Filled missing Embarked with mode: S\n",
      "Null check:\n",
      " PassengerId    0\n",
      "Survived       0\n",
      "Pclass         0\n",
      "Name           0\n",
      "Sex            0\n",
      "Age            0\n",
      "SibSp          0\n",
      "Parch          0\n",
      "Ticket         0\n",
      "Fare           0\n",
      "Cabin          0\n",
      "Embarked       0\n",
      "dtype: int64\n",
      "\n",
      "3. VISUALIZING OUTLIERS\n",
      "\n",
      "4. ENCODING CATEGORICAL DATA\n",
      "Converted Sex and Embarked to numbers.\n",
      "\n",
      "5. NORMALIZING NUMERICAL DATA\n",
      "Normalized Age and Fare.\n",
      "\n",
      "CLEANED DATA\n",
      "   PassengerId  Survived  Pclass  \\\n",
      "0            1         0       3   \n",
      "1            2         1       1   \n",
      "2            3         1       3   \n",
      "3            4         1       1   \n",
      "4            5         0       3   \n",
      "\n",
      "                                                Name       Age  SibSp  Parch  \\\n",
      "0                            Braund, Mr. Owen Harris -0.592481      1      0   \n",
      "1  Cumings, Mrs. John Bradley (Florence Briggs Th...  0.638789      1      0   \n",
      "2                             Heikkinen, Miss. Laina -0.284663      0      0   \n",
      "3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  0.407926      1      0   \n",
      "4                           Allen, Mr. William Henry  0.407926      0      0   \n",
      "\n",
      "             Ticket      Fare    Cabin  Sex_male  Embarked_Q  Embarked_S  \n",
      "0         A/5 21171 -0.502445  Unknown      True       False        True  \n",
      "1          PC 17599  0.786845      C85     False       False       False  \n",
      "2  STON/O2. 3101282 -0.488854  Unknown     False       False        True  \n",
      "3            113803  0.420730     C123     False       False        True  \n",
      "4            373450 -0.486337  Unknown      True       False        True  \n",
      "\n",
      "PROCESS COMPLETE: Saved 'cleaned_data.csv'\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "url = \"https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv\"\n",
    "df = pd.read_csv(url)\n",
    "print(\"1. RAW DATA INFO\")\n",
    "print(f\"Shape: {df.shape}\")\n",
    "print(df.head())\n",
    "print(\"\\nData Types:\")\n",
    "print(df.dtypes)\n",
    "print(\"\\nMissing Values:\")\n",
    "print(df.isnull().sum())\n",
    "mean_age = df['Age'].mean()\n",
    "df['Age'] = df['Age'].fillna(mean_age)\n",
    "print(f\"Filled missing Age with mean: {mean_age}\")\n",
    "df['Cabin'] = df['Cabin'].fillna(\"Unknown\")\n",
    "mode_embarked = df['Embarked'].mode()[0]\n",
    "df['Embarked'] = df['Embarked'].fillna(mode_embarked)\n",
    "print(f\"Filled missing Embarked with mode: {mode_embarked}\")\n",
    "print(\"Null check:\\n\", df.isnull().sum())\n",
    "print(\"\\n3. VISUALIZING OUTLIERS\")\n",
    "plt.figure(figsize=(10, 5))\n",
    "sns.boxplot(x=df['Age'])\n",
    "plt.title(\"Age Boxplot (Checking for Outliers)\")\n",
    "plt.savefig('outliers_age.png')\n",
    "plt.close()\n",
    "print(\"\\n4. ENCODING CATEGORICAL DATA\")\n",
    "df = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)\n",
    "print(\"Converted Sex and Embarked to numbers.\")\n",
    "print(\"\\n5. NORMALIZING NUMERICAL DATA\")\n",
    "numerical_cols = ['Age', 'Fare']\n",
    "scaler = StandardScaler()\n",
    "df[numerical_cols] = scaler.fit_transform(df[numerical_cols])\n",
    "print(\"Normalized Age and Fare.\")\n",
    "print(\"\\nCLEANED DATA\")\n",
    "print(df.head())\n",
    "df.to_csv('cleaned_data.csv', index=False)\n",
    "print(\"\\nPROCESS COMPLETE: Saved 'cleaned_data.csv'\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2607aac4-a272-4471-bf98-ebdb755f3fc0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
